### Atividade de Laboratório - Redes Neurais

**Aluno:** Yan Victor Sirianni Azevedo

Import do dataset da planta iris:

In [3]:
from sklearn import datasets
import numpy as np
import random 

data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

**Funções auxiliares para implementação do Perceptron:**

In [61]:
def input_eval(W, x): #Avalia um elemento da amostra com base no conjunto de pesos
    
    _, LEN_WEIGHTS = W.shape
    BIAS_POS = LEN_WEIGHTS - 1 

    Weights = []
    Weights.append(W[0][0:len(W[0])-1])
    Weights.append(W[1][0:len(W[1])-1])
    Weights.append(W[2][0:len(W[2])-1])
    bias = []
    bias.append(W[0][BIAS_POS])
    bias.append(W[1][BIAS_POS])
    bias.append(W[2][BIAS_POS])

    result = np.zeros((len(W), 1))
  
    for i in range(0, len(W)):
        result[i][0] = np.dot(Weights[i], x) + bias[i]
    
    return result

In [18]:
def update_weights(W, alpha, e, x): #Atualiza os pesos dos neurônios
    
  # Weights update
    W[:, 0:4] += alpha * np.dot(e, x.reshape(1, -1))
  
  # Bias update
    W[:, 4] = W[:, 4] + np.squeeze(np.asarray((alpha * e)))
    return W

In [11]:
def calc_error(u, expected): #Avalia o erro de classificação
    
    error = np.zeros((len(u), 1))
    for i in range(0, len(u)):
        if expected == i:
            error[i][0] = 1 - u[i][0]
        else:
            error[i][0] = 0 - u[i][0]
    return error

**Função de ativação degrau:**
    
Dado o pertencimento avaliado utiliza a função degrau para determinar a ativação do neurônio.

In [8]:
def step_activation(u): 
    
    return np.where(u >= 0, 1, 0)

**Função Sigmoide:**
    
Dado o pertencimento avaliado utiliza a função sigmoidal (também conhecida como logística) para determinar a ativação do neurônio.  

In [7]:
def sigmoid_activation(t): 
    
    sigmoid_applied = 1/(1 + np.exp(-t))
    non_actived = np.zeros_like(sigmoid_applied)
    non_actived[sigmoid_applied.argmax(0), 0] = 1
    actived = non_actived
    return actived

**Implementação do Perceptron:**

In [71]:
def Perceptron(max_it, alpha, X, D, activation_func):
    
    W = np.zeros((3,5))
    t = 1
    E = 1
    e = []
    Eacum = []
    
    while t < max_it and E > 0:
        E = 0
        poss = list(range(0, len(D)))
        
        for k in range(0, len(D)):
        
            j = random.randint(0, len(poss)-1)
            i = poss[j]
            poss.pop(j)

            y = None
        
            if(activation_func == 'sigmoid'):
                y = sigmoid_activation(input_eval(W, X[i]))
                print(y)
            elif(activation_func == 'step'):
                y = step_activation(input_eval(W, X[i]))   
                print(input_eval(W, X[i]))

            e.append(calc_error(y, D[i]))
            W = update_weights(W, alpha, e[len(e)-1], X[i])
            E += np.sum(np.square(e[len(e)-1]))
        
        t += 1
        Eacum.append(E)    
    return W

## Teste da função

In [73]:
W = Perceptron(100, 0.1, data.data, data.target, 'step')

W

[[0.]
 [0.]
 [0.]]
[[-7.508]
 [-7.508]
 [ 0.   ]]
[[-8.087]
 [-8.087]
 [ 0.   ]]
[[-7.024]
 [-7.024]
 [ 0.   ]]
[[-7.362]
 [-0.609]
 [-6.753]]
[[-5.692]
 [ 5.031]
 [-5.247]]
[[-4.85 ]
 [ 4.452]
 [-4.581]]
[[-2.452]
 [ 1.631]
 [-5.886]]
[[-1.126]
 [-3.177]
 [-0.594]]
[[ 2.429]
 [-3.141]
 [-0.582]]
[[ 2.491]
 [-5.797]
 [-0.748]]
[[-6.523]
 [-4.105]
 [ 7.96 ]]
[[-7.61 ]
 [ 2.169]
 [ 2.325]]
[[-4.026]
 [ 1.281]
 [-4.153]]
[[-3.325]
 [-3.145]
 [-5.788]]
[[-2.703]
 [-2.917]
 [ 3.009]]
[[-2.32 ]
 [-3.309]
 [ 2.972]]
[[-3.179]
 [ 5.563]
 [-5.246]]
[[-2.483]
 [-3.479]
 [ 3.304]]
[[-2.821]
 [ 5.085]
 [-5.085]]
[[ 0.148]
 [-2.795]
 [ 1.386]]
[[-1.945]
 [-3.663]
 [-1.568]]
[[-2.925]
 [ 3.918]
 [-1.083]]
[[ 0.746]
 [-3.782]
 [ 2.926]]
[[ 0.354]
 [-3.541]
 [-1.619]]
[[-3.197]
 [-5.366]
 [ 2.411]]
[[-1.835]
 [-4.266]
 [ 0.951]]
[[ 0.592]
 [ 1.298]
 [-7.327]]
[[-2.16 ]
 [-3.492]
 [-4.846]]
[[ 0.688]
 [ 0.758]
 [-6.108]]
[[-2.42 ]
 [-1.438]
 [-4.94 ]]
[[-2.345]
 [-1.175]
 [ 2.071]]
[[-2.659]
 [ 5.785]


[[-2.482]
 [-2.516]
 [ 3.711]]
[[ 0.456]
 [-3.358]
 [-9.762]]
[[-1.199]
 [-1.981]
 [-1.639]]
[[ 0.299]
 [ 0.179]
 [-9.035]]
[[  0.459]
 [ -3.863]
 [-10.845]]
[[  0.427]
 [ -3.807]
 [-11.317]]
[[-1.448]
 [-0.388]
 [-1.515]]
[[-2.588]
 [ 5.022]
 [ 3.835]]
[[-2.995]
 [-4.34 ]
 [ 6.514]]
[[-2.986]
 [-3.244]
 [ 5.512]]
[[  0.322]
 [ -4.136]
 [-10.291]]
[[-2.268]
 [-2.083]
 [ 2.193]]
[[-2.483]
 [ 5.414]
 [-4.938]]
[[-1.969]
 [ 5.   ]
 [-4.459]]
[[-2.979]
 [ 5.631]
 [-1.888]]
[[-3.078]
 [-2.907]
 [ 7.259]]
[[-2.194]
 [-3.942]
 [ 2.312]]
[[  0.265]
 [  1.357]
 [-14.237]]
[[-2.371]
 [-1.472]
 [-3.379]]
[[-1.871]
 [ 5.945]
 [-5.699]]
[[-2.634]
 [ 6.623]
 [-2.13 ]]
[[-2.777]
 [-0.809]
 [ 5.497]]
[[  0.357]
 [ -3.197]
 [-10.635]]
[[-2.189]
 [ 1.549]
 [ 2.048]]
[[-2.462]
 [-0.266]
 [-2.934]]
[[  0.551]
 [ -4.604]
 [-11.684]]
[[-2.049]
 [-1.933]
 [ 2.252]]
[[-2.847]
 [ 7.456]
 [-1.803]]
[[-2.838]
 [-2.825]
 [ 7.572]]
[[-3.992]
 [ 1.496]
 [11.487]]
[[ -2.821]
 [-11.626]
 [  6.284]]
[[  0.455]
 [ -9.7

[[-2.194]
 [-7.673]
 [ 1.436]]
[[-2.974]
 [ 3.258]
 [-3.554]]
[[-2.713]
 [-8.473]
 [ 6.776]]
[[  0.293]
 [ -8.913]
 [-16.581]]
[[-1.925]
 [-6.964]
 [ 1.393]]
[[  0.299]
 [ -1.96 ]
 [-18.349]]
[[-1.969]
 [ 0.687]
 [-3.252]]
[[  0.516]
 [ -2.15 ]
 [-23.457]]
[[-2.659]
 [ 0.038]
 [ 0.168]]
[[ -2.225]
 [  0.261]
 [-11.823]]
[[-2.821]
 [-1.289]
 [-8.819]]
[[  0.203]
 [ -1.868]
 [-17.789]]
[[  0.393]
 [ -2.879]
 [-20.618]]
[[-3.328]
 [ 0.047]
 [ 2.091]]
[[  0.551]
 [-10.313]
 [-22.978]]
[[-1.884]
 [-8.724]
 [-4.089]]
[[-2.244]
 [-1.656]
 [-2.996]]
[[-2.16 ]
 [ 4.123]
 [-2.233]]
[[-1.871]
 [ 3.497]
 [-4.59 ]]
[[  0.084]
 [  3.051]
 [-15.718]]
[[  0.746]
 [ -3.404]
 [-25.634]]
[[-1.963]
 [ 0.107]
 [-6.397]]
[[  0.427]
 [ -2.669]
 [-22.091]]
[[-1.838]
 [ 0.786]
 [-4.702]]
[[-3.992]
 [ 2.68 ]
 [ 6.943]]
[[  0.459]
 [ -8.58 ]
 [-21.045]]
[[ -3.492]
 [-13.214]
 [  2.2  ]]
[[ -2.482]
 [-10.392]
 [ -0.268]]
[[-2.32 ]
 [-9.414]
 [ 3.58 ]]
[[-2.051]
 [-2.16 ]
 [-5.35 ]]
[[-2.177]
 [ 4.058]
 [-1.458]]


[[-2.345]
 [-3.48 ]
 [ 5.278]]
[[  0.194]
 [ -2.312]
 [-21.368]]
[[  0.315]
 [ -1.678]
 [-22.886]]
[[-2.371]
 [-1.931]
 [-0.404]]
[[-3.992]
 [12.876]
 [ 8.26 ]]
[[-3.201]
 [ 0.742]
 [ 4.066]]
[[-1.913]
 [-7.603]
 [-3.356]]
[[  0.746]
 [ -4.934]
 [-29.336]]
[[-2.625]
 [-5.157]
 [ 3.502]]
[[-1.741]
 [-2.112]
 [-6.128]]
[[-2.189]
 [ 6.265]
 [-3.608]]
[[-2.051]
 [ 2.68 ]
 [-5.324]]
[[-2.462]
 [ 2.898]
 [-0.248]]
[[-2.404]
 [-4.831]
 [ 9.782]]
[[-1.443]
 [-1.902]
 [-0.4  ]]
[[  0.419]
 [ -0.322]
 [-19.148]]
[[-2.986]
 [-0.049]
 [10.786]]
[[  0.312]
 [ -0.402]
 [-19.652]]
[[  0.456]
 [  0.102]
 [-17.444]]
[[  0.148]
 [ -2.549]
 [-15.918]]
[[-1.871]
 [-2.678]
 [ 1.562]]
[[-2.53 ]
 [ 6.173]
 [ 0.011]]
[[  0.265]
 [  2.229]
 [-26.136]]
[[-3.72 ]
 [ 2.484]
 [-3.297]]
[[ -3.492]
 [-14.118]
 [  6.253]]
[[-2.847]
 [-9.861]
 [ 5.158]]
[[ -3.325]
 [-14.461]
 [ 10.485]]
[[-2.584]
 [-8.879]
 [ 2.066]]
[[-1.835]
 [-9.306]
 [-0.795]]
[[-1.785]
 [-1.679]
 [-3.1  ]]
[[-2.821]
 [ 2.11 ]
 [ 3.689]]
[[-1.656]

[[-1.959]
 [-8.179]
 [-5.686]]
[[-2.847]
 [-2.546]
 [ 2.944]]
[[-3.179]
 [-3.378]
 [ 7.075]]
[[-1.935]
 [-3.254]
 [-4.233]]
[[  0.376]
 [  0.51 ]
 [-25.19 ]]
[[-1.665]
 [ 2.89 ]
 [-3.935]]
[[-3.219]
 [-0.264]
 [ 0.703]]
[[  0.299]
 [ -2.552]
 [-23.193]]
[[-2.847]
 [ 0.942]
 [ 3.816]]
[[-2.704]
 [-3.664]
 [ 3.174]]
[[-3.392]
 [-5.723]
 [ 4.777]]
[[-2.345]
 [-4.103]
 [-0.685]]
[[  0.293]
 [ -5.7  ]
 [-27.12 ]]
[[  0.365]
 [ -4.95 ]
 [-27.281]]
[[-3.325]
 [-4.135]
 [ 9.77 ]]
[[  0.33 ]
 [ -4.665]
 [-24.324]]
[[-3.328]
 [ 0.203]
 [ 4.476]]
[[-1.448]
 [-6.924]
 [-9.092]]
[[-2.404]
 [-3.93 ]
 [ 4.797]]
[[  0.569]
 [ -7.982]
 [-29.54 ]]
[[-2.051]
 [-4.318]
 [-5.249]]
[[-2.979]
 [ 4.882]
 [ 4.712]]
[[  0.3  ]
 [ -4.794]
 [-24.168]]
[[  0.592]
 [ -9.554]
 [-31.446]]
[[-3.325]
 [-7.985]
 [ 9.77 ]]
[[-1.969]
 [-1.527]
 [-2.344]]
[[  0.284]
 [  0.796]
 [-24.846]]
[[-2.625]
 [-3.999]
 [ 4.949]]
[[  0.459]
 [ -5.265]
 [-27.501]]
[[-1.665]
 [ 1.185]
 [-3.935]]
[[-3.628]
 [-0.185]
 [ 6.738]]
[[-2.268]

[[-3.628]
 [ 7.313]
 [ 7.39 ]]
[[ -2.838]
 [-10.198]
 [  5.236]]
[[-1.884]
 [-0.384]
 [-6.072]]
[[  0.025]
 [ -1.805]
 [-24.654]]
[[  0.203]
 [ -1.505]
 [-25.106]]
[[-2.268]
 [ 1.88 ]
 [-2.419]]
[[  0.224]
 [ -1.04 ]
 [-26.411]]
[[-2.986]
 [-0.5  ]
 [ 4.177]]
[[-2.32 ]
 [ 2.11 ]
 [-4.821]]
[[-3.052]
 [-0.7  ]
 [ 4.993]]
[[-1.998]
 [ 1.65 ]
 [-6.97 ]]
[[-2.973]
 [ 4.895]
 [ 4.709]]
[[-2.925]
 [-7.767]
 [ 3.72 ]]
[[  0.202]
 [ -5.45 ]
 [-24.034]]
[[  0.33 ]
 [ -8.136]
 [-26.404]]
[[  0.284]
 [ -5.056]
 [-26.83 ]]
[[-2.16 ]
 [-5.187]
 [-2.183]]
[[-2.121]
 [ 1.178]
 [-7.612]]
[[-3.992]
 [ 4.422]
 [11.869]]
[[  0.134]
 [ -6.448]
 [-25.77 ]]
[[ -2.666]
 [-12.425]
 [  1.519]]
[[  0.516]
 [ -8.763]
 [-32.025]]
[[-2.196]
 [-8.961]
 [-5.251]]
[[  0.419]
 [ -3.664]
 [-29.635]]
[[-1.988]
 [-0.538]
 [-3.272]]
[[-1.969]
 [ 6.439]
 [-2.433]]
[[-2.704]
 [ 8.828]
 [ 3.578]]
[[-2.138]
 [ 0.081]
 [-5.874]]
[[  0.293]
 [ -5.7  ]
 [-29.434]]
[[-2.847]
 [-1.255]
 [ 4.178]]
[[-2.189]
 [ 2.01 ]
 [-3.313]]
[[ 

[[  0.203]
 [ -0.954]
 [-25.193]]
[[-2.974]
 [ 6.34 ]
 [ 3.554]]
[[-2.268]
 [-4.742]
 [-0.265]]
[[-2.584]
 [ 3.449]
 [ 2.789]]
[[  0.265]
 [ -5.696]
 [-26.766]]
[[  0.25 ]
 [ -5.534]
 [-27.186]]
[[-2.777]
 [-8.805]
 [ 6.285]]
[[  0.592]
 [-12.909]
 [-34.412]]
[[-2.552]
 [-5.571]
 [ 3.865]]
[[  0.643]
 [-11.216]
 [-34.71 ]]
[[ -3.09 ]
 [-10.56 ]
 [  9.824]]
[[-2.225]
 [-4.831]
 [-1.597]]
[[-3.179]
 [ 0.627]
 [10.694]]
[[  0.224]
 [ -6.301]
 [-26.507]]
[[-1.988]
 [-5.408]
 [-1.378]]
[[-1.998]
 [ 0.396]
 [-5.004]]
[[  0.42 ]
 [ -4.258]
 [-30.917]]
[[-1.199]
 [-0.522]
 [-8.084]]
[[-3.492]
 [ 5.666]
 [ 8.212]]
[[-2.751]
 [-4.516]
 [ 8.138]]
[[-1.785]
 [-1.444]
 [-3.956]]
[[-3.201]
 [ 6.073]
 [ 9.317]]
[[  0.393]
 [ -7.464]
 [-29.178]]
[[  0.312]
 [ -7.887]
 [-31.029]]
[[  0.232]
 [ -6.518]
 [-26.696]]
[[-3.18 ]
 [-6.293]
 [ 8.089]]
[[-2.345]
 [-2.036]
 [ 1.673]]
[[  0.084]
 [  1.693]
 [-25.962]]
[[-2.316]
 [-0.586]
 [-9.488]]
[[-3.108]
 [ 6.882]
 [-2.808]]
[[  0.356]
 [ -5.283]
 [-27.487]]


[[-1.656]
 [ 3.291]
 [-6.902]]
[[-2.42 ]
 [-0.772]
 [ 1.74 ]]
[[-3.09 ]
 [-3.089]
 [ 8.656]]
[[-1.838]
 [ 2.342]
 [-5.632]]
[[-3.108]
 [ 2.38 ]
 [ 3.84 ]]
[[-2.703]
 [-7.043]
 [ 4.868]]
[[-2.163]
 [-8.38 ]
 [-0.728]]
[[  0.365]
 [ -4.567]
 [-32.822]]
[[  0.293]
 [ -5.541]
 [-32.542]]
[[-2.135]
 [ 1.103]
 [-1.27 ]]
[[-3.179]
 [-2.259]
 [ 9.582]]
[[  0.419]
 [ -3.593]
 [-32.864]]
[[  0.148]
 [ -1.794]
 [-28.07 ]]
[[  0.134]
 [ -1.104]
 [-28.552]]
[[  0.427]
 [ -3.941]
 [-34.514]]
[[-2.973]
 [ 2.975]
 [ 6.102]]
[[-2.974]
 [-6.934]
 [ 1.868]]
[[-2.177]
 [-9.14 ]
 [ 0.228]]
[[ -1.925]
 [ -1.638]
 [-10.517]]
[[-2.53 ]
 [ 7.637]
 [-5.458]]
[[-1.665]
 [ 7.08 ]
 [-9.205]]
[[ -2.225]
 [  6.086]
 [-10.095]]
[[  0.232]
 [  1.008]
 [-33.954]]
[[-2.244]
 [ 2.431]
 [-9.419]]
[[-3.628]
 [ 2.453]
 [ 1.063]]
[[ -3.325]
 [-14.156]
 [  5.197]]
[[  0.291]
 [ -9.622]
 [-36.407]]
[[-2.751]
 [-9.447]
 [ 0.42 ]]
[[ -1.787]
 [ -7.983]
 [-13.515]]
[[  0.194]
 [ -4.882]
 [-33.592]]
[[-1.969e+00]
 [-2.000e-03]
 [-

[[-2.244]
 [ 0.037]
 [-0.404]]
[[-2.588]
 [-5.223]
 [ 5.148]]
[[-2.847]
 [-3.068]
 [ 7.67 ]]
[[  0.427]
 [ -4.266]
 [-34.546]]
[[-2.138]
 [-0.619]
 [-3.249]]
[[-1.871]
 [ 4.721]
 [-3.438]]
[[-2.853]
 [ 0.892]
 [13.602]]
[[-3.104]
 [-3.868]
 [13.114]]
[[-3.72 ]
 [ 0.566]
 [14.028]]
[[ -1.518]
 [-11.091]
 [ -6.369]]
[[  0.293]
 [ -7.264]
 [-32.408]]
[[  0.456]
 [ -3.365]
 [-29.779]]
[[-2.811]
 [-9.807]
 [ 9.549]]
[[  0.355]
 [ -4.474]
 [-28.9  ]]
[[  0.365]
 [ -6.05 ]
 [-32.856]]
[[-1.838]
 [-2.936]
 [-3.464]]
[[-1.656]
 [ 3.964]
 [-4.974]]
[[-2.868]
 [ 1.452]
 [ 7.702]]
[[-2.316]
 [-4.41 ]
 [-1.334]]
[[-2.713]
 [-0.535]
 [ 6.934]]
[[  0.466]
 [  0.276]
 [-32.502]]
[[-2.482]
 [-5.206]
 [ 4.89 ]]
[[-2.771]
 [-4.419]
 [11.64 ]]
[[  0.746]
 [ -6.224]
 [-40.278]]
[[-2.704]
 [ 0.157]
 [ 7.791]]
[[  0.33 ]
 [ -9.43 ]
 [-29.273]]
[[-2.973]
 [-7.353]
 [ 9.216]]
[[ -2.163]
 [-10.529]
 [  0.367]]
[[-3.325]
 [-8.827]
 [ 8.657]]
[[  0.148]
 [ -2.509]
 [-32.561]]
[[-2.552]
 [-3.724]
 [-1.682]]
[[-3.0

 [ 8.815]]
[[-2.703]
 [-1.347]
 [ 4.646]]
[[-3.201]
 [ 1.287]
 [ 8.083]]
[[  0.106]
 [-12.926]
 [-33.287]]
[[-2.584]
 [-8.652]
 [ 0.454]]
[[  0.203]
 [ -8.889]
 [-31.608]]
[[ -2.838]
 [-15.826]
 [  6.531]]
[[ -2.634]
 [-11.446]
 [  3.827]]
[[-1.871]
 [-9.524]
 [-7.171]]
[[-2.847]
 [-3.057]
 [ 5.373]]
[[-2.371]
 [-6.311]
 [ 0.345]]
[[-2.666]
 [ 0.743]
 [-5.715]]
[[-1.518]
 [-5.435]
 [-9.291]]
[[-2.189]
 [ 5.564]
 [-3.08 ]]
[[-3.328]
 [ 2.552]
 [ 7.714]]
[[-2.268]
 [-6.105]
 [-2.269]]
[[-2.163]
 [-0.142]
 [-2.522]]
[[  0.44 ]
 [  0.774]
 [-36.716]]
[[-1.988]
 [ 2.657]
 [-3.431]]
[[  0.408]
 [ -4.431]
 [-36.722]]
[[  0.427]
 [ -3.089]
 [-38.478]]
[[  0.459]
 [ -2.889]
 [-37.047]]
[[-1.785]
 [ 3.913]
 [-6.328]]
[[-1.884]
 [ 2.049]
 [-5.28 ]]
[[-3.628]
 [ 5.226]
 [10.5  ]]
[[-2.53 ]
 [-4.133]
 [ 1.395]]
[[ -1.422]
 [  1.243]
 [-13.402]]
[[  0.084]
 [  0.431]
 [-31.065]]
[[  0.232]
 [ -5.469]
 [-36.121]]
[[  0.398]
 [ -6.676]
 [-41.526]]
[[-3.09 ]
 [-8.475]
 [ 1.181]]
[[  0.569]
 [-10.365]
 

[[-2.838]
 [-6.034]
 [ 6.665]]
[[-1.838]
 [ 0.754]
 [-7.286]]
[[-1.963]
 [-1.083]
 [-9.871]]
[[-1.741]
 [ 6.759]
 [-8.628]]
[[  0.419]
 [  1.113]
 [-37.703]]
[[-2.483]
 [ 1.63 ]
 [-2.016]]
[[  0.456]
 [ -1.659]
 [-33.99 ]]
[[-1.935]
 [-0.118]
 [-5.874]]
[[  0.569]
 [ -0.962]
 [-40.548]]
[[-3.325]
 [ 5.383]
 [13.14 ]]
[[-1.884]
 [ 0.349]
 [-6.232]]
[[  0.354]
 [ -5.501]
 [-36.307]]
[[  0.084]
 [  0.765]
 [-27.842]]
[[-2.163]
 [-4.891]
 [-1.959]]
[[  0.078]
 [ -2.283]
 [-31.65 ]]
[[ -1.199]
 [  1.574]
 [-11.818]]
[[  0.291]
 [ -2.377]
 [-36.196]]
[[-2.838]
 [-1.91 ]
 [ 6.665]]
[[-2.847]
 [ 2.9  ]
 [ 3.776]]
[[  0.33 ]
 [ -7.912]
 [-33.691]]
[[-1.935]
 [-6.353]
 [-5.874]]
[[-2.771]
 [ 1.44 ]
 [ 8.537]]
[[-1.884]
 [ 0.164]
 [-7.822]]
[[  0.688]
 [ -9.008]
 [-38.808]]
[[-2.194]
 [-7.362]
 [-4.827]]
[[-2.16 ]
 [ 3.158]
 [-3.088]]
[[-1.827]
 [ 4.481]
 [-8.778]]
[[  0.232]
 [ -0.839]
 [-32.505]]
[[-3.201]
 [ 6.102]
 [ 7.913]]
[[  0.456]
 [ -5.399]
 [-33.99 ]]
[[-1.945]
 [-4.847]
 [-8.849]]
[[-

[[-2.666]
 [ 2.135]
 [ 6.254]]
[[-2.811]
 [-7.259]
 [ 9.945]]
[[  0.232]
 [ -3.366]
 [-31.467]]
[[  0.106]
 [ -6.497]
 [-32.321]]
[[-3.104]
 [-4.148]
 [13.718]]
[[-3.72 ]
 [ 0.311]
 [14.345]]
[[ -1.945]
 [-10.794]
 [ -5.881]]
[[-1.935]
 [-5.936]
 [-2.856]]
[[-2.482]
 [ 0.539]
 [ 4.683]]
[[  0.398]
 [ -5.542]
 [-36.634]]
[[-2.868]
 [-5.619]
 [ 7.615]]
[[-1.835]
 [-5.514]
 [-3.973]]
[[-2.838]
 [-3.845]
 [10.711]]
[[-2.194]
 [-0.557]
 [-1.485]]
[[-3.301]
 [12.987]
 [ 9.983]]
[[  0.569]
 [ -4.899]
 [-39.406]]
[[  0.265]
 [ -0.088]
 [-32.897]]
[[-1.518]
 [-1.176]
 [-7.585]]
[[  0.393]
 [  1.85 ]
 [-35.752]]
[[  0.365]
 [ -2.563]
 [-36.647]]
[[  0.169]
 [ -0.355]
 [-31.299]]
[[-2.974]
 [ 4.298]
 [ 4.676]]
[[-2.42 ]
 [-8.852]
 [ 4.366]]
[[-2.552]
 [-7.154]
 [ 5.297]]
[[-2.771]
 [-7.507]
 [12.145]]
[[  0.44]
 [ -7.86]
 [-36.7 ]]
[[-2.171]
 [-6.687]
 [-1.473]]
[[-3.219]
 [-1.192]
 [ 5.339]]
[[  0.459]
 [ -2.458]
 [-37.1  ]]
[[-2.986]
 [-2.259]
 [ 9.35 ]]
[[  0.315]
 [ -1.863]
 [-34.772]]
[[-3.3

[[-1.835]
 [-5.799]
 [-2.772]]
[[-2.974]
 [ 3.664]
 [ 6.302]]
[[ -2.986]
 [-10.987]
 [ 11.145]]
[[-1.959]
 [-6.403]
 [-3.618]]
[[-2.244]
 [ 2.081]
 [-0.106]]
[[  0.393]
 [ -2.877]
 [-35.374]]
[[  0.455]
 [ -3.168]
 [-35.71 ]]
[[-2.345]
 [ 2.735]
 [ 3.776]]
[[-3.328]
 [-1.091]
 [ 4.299]]
[[  0.551]
 [ -4.1  ]
 [-45.104]]
[[  0.466]
 [ -1.404]
 [-40.358]]
[[  0.078]
 [ -2.612]
 [-34.667]]
[[ -1.827]
 [  2.296]
 [-11.308]]
[[-2.703]
 [ 0.029]
 [ 2.595]]
[[-1.751]
 [-4.094]
 [-9.369]]
[[  0.232]
 [ -1.546]
 [-35.53 ]]
[[  0.357]
 [ -2.637]
 [-40.786]]
[[  0.459]
 [ -2.952]
 [-41.359]]
[[-1.935]
 [-2.872]
 [-8.101]]
[[-2.625]
 [ 2.531]
 [ 5.07 ]]
[[-2.16 ]
 [-0.59 ]
 [-5.269]]
[[-2.196]
 [ 5.281]
 [-9.251]]
[[ 3.5400e-01]
 [ 2.5000e-02]
 [-3.9469e+01]]
[[ -1.884]
 [  4.862]
 [-10.448]]
[[-2.051]
 [-1.32 ]
 [-9.696]]
[[-2.42 ]
 [ 5.288]
 [-1.04 ]]
[[-3.247]
 [-5.062]
 [14.546]]
[[-2.049]
 [-3.141]
 [-0.414]]
[[-1.518]
 [ 5.046]
 [-6.218]]
[[  0.203]
 [  3.949]
 [-30.522]]
[[  0.643]
 [ -3.54

[[-2.049]
 [-4.347]
 [-5.208]]
[[-2.32 ]
 [ 7.016]
 [-6.233]]
[[-3.628]
 [ 9.334]
 [10.526]]
[[-2.53 ]
 [-0.359]
 [ 0.613]]
[[ -2.189]
 [  7.838]
 [-11.418]]
[[-2.483]
 [ 4.298]
 [-9.524]]
[[  0.134]
 [  2.752]
 [-40.104]]
[[-2.751]
 [-1.119]
 [ 0.676]]
[[-3.992]
 [ 2.543]
 [ 7.363]]
[[  0.354]
 [-11.803]
 [-43.796]]
[[ -2.051]
 [-11.335]
 [-14.692]]
[[ -1.665]
 [  1.875]
 [-11.405]]
[[  0.232]
 [ -3.006]
 [-39.487]]
[[-3.052]
 [-5.91 ]
 [-0.705]]
[[-3.078]
 [-3.356]
 [11.244]]
[[  0.17 ]
 [ -6.632]
 [-33.564]]
[[  0.322]
 [ -3.906]
 [-38.302]]
[[  0.315]
 [ -3.973]
 [-37.734]]
[[-2.625]
 [-4.689]
 [ 8.814]]
[[-3.197]
 [-5.579]
 [11.242]]
[[-2.838]
 [-7.924]
 [ 9.24 ]]
[[  0.516]
 [ -4.51 ]
 [-42.85 ]]
[[-1.925]
 [-2.317]
 [-5.096]]
[[-2.666]
 [ 0.743]
 [ 4.37 ]]
[[-2.771]
 [-4.385]
 [10.784]]
[[-2.777]
 [-7.653]
 [ 6.924]]
[[-1.871]
 [-3.437]
 [-6.624]]
[[  0.084]
 [  3.116]
 [-29.482]]
[[-1.422]
 [ 0.284]
 [-8.378]]
[[-1.787]
 [-1.046]
 [-8.524]]
[[ -1.199]
 [  3.949]
 [-11.68 ]]
[[-

[[  0.516]
 [ -8.442]
 [-43.853]]
[[-2.925]
 [-8.79 ]
 [ 7.899]]
[[-2.979]
 [-6.426]
 [ 9.291]]
[[-3.18 ]
 [-7.919]
 [ 9.729]]
[[-1.422]
 [-3.761]
 [-8.218]]
[[-3.72 ]
 [ 2.467]
 [13.54 ]]
[[-2.138]
 [-8.843]
 [-6.37 ]]
[[ -1.448]
 [ -0.801]
 [-12.232]]
[[  0.106]
 [ -2.357]
 [-35.89 ]]
[[  0.134]
 [  1.906]
 [-35.396]]
[[-2.163]
 [-2.688]
 [-0.027]]
[[-3.219]
 [ 5.106]
 [ 3.964]]
[[-3.052]
 [-7.811]
 [ 9.949]]
[[  0.078]
 [ -6.681]
 [-33.818]]
[[  0.312]
 [ -7.767]
 [-42.165]]
[[  0.455]
 [ -7.404]
 [-39.948]]
[[-2.853]
 [-8.16 ]
 [14.274]]
[[-2.244]
 [-1.591]
 [-2.988]]
[[-2.462]
 [ 2.208]
 [ 3.294]]
[[  0.357]
 [ -6.361]
 [-40.319]]
[[-2.552]
 [-4.361]
 [ 4.179]]
[[-1.827]
 [-1.411]
 [-8.023]]
[[-2.666]
 [-1.493]
 [ 5.158]]
[[ 2.2400e-01]
 [-9.0000e-03]
 [-3.6281e+01]]
[[-2.838]
 [-3.082]
 [10.195]]
[[ 2.5000e-02]
 [-6.6000e-01]
 [-3.3842e+01]]
[[-3.301]
 [ 5.394]
 [ 8.927]]
[[-1.751]
 [-2.973]
 [-6.245]]
[[-2.404]
 [-0.885]
 [ 8.902]]
[[-3.09 ]
 [-5.383]
 [12.53 ]]
[[-2.135]
 [ 1.9

[[  0.293]
 [ -5.427]
 [-42.076]]
[[-2.666]
 [-3.466]
 [ 3.919]]
[[-1.785]
 [ 2.833]
 [-7.849]]
[[-3.992]
 [ 4.026]
 [18.339]]
[[  0.376]
 [ -7.654]
 [-39.35 ]]
[[-2.345]
 [-4.845]
 [-0.145]]
[[  0.25 ]
 [ -1.581]
 [-39.183]]
[[-2.771]
 [-2.418]
 [10.752]]
[[-3.219]
 [-4.486]
 [ 2.372]]
[[  0.205]
 [ -2.907]
 [-41.154]]
[[ -1.518]
 [ -3.082]
 [-10.887]]
[[ -2.121]
 [  5.069]
 [-10.158]]
[[-2.925]
 [ 3.406]
 [ 6.677]]
[[-1.835]
 [-4.264]
 [-6.963]]
[[-2.138]
 [ 4.79 ]
 [-7.887]]
[[  0.299]
 [  0.647]
 [-36.346]]
[[  0.232]
 [ -3.616]
 [-38.434]]
[[-2.049]
 [-5.072]
 [-5.06 ]]
[[  0.134]
 [  3.64 ]
 [-37.258]]
[[-3.104]
 [-0.158]
 [12.218]]
[[-1.741]
 [ 1.736]
 [-9.22 ]]
[[-1.871]
 [ 0.684]
 [-7.692]]
[[-2.32 ]
 [ 1.353]
 [-6.121]]
[[-1.998]
 [ 1.   ]
 [-9.262]]
[[  0.408]
 [ -5.134]
 [-42.505]]
[[-2.316]
 [ 3.218]
 [-5.662]]
[[  0.33 ]
 [ -3.785]
 [-38.005]]
[[  0.354]
 [ -5.186]
 [-40.88 ]]
[[-2.189]
 [ 5.016]
 [-4.307]]
[[-2.163]
 [-0.524]
 [-1.289]]
[[-2.777]
 [ 5.05 ]
 [ 6.627]]
[[-

[[  0.466]
 [ -6.676]
 [-43.784]]
[[  0.106]
 [ -9.66 ]
 [-39.59 ]]
[[-1.835]
 [-6.023]
 [-5.137]]
[[-1.838]
 [ 1.608]
 [-9.538]]
[[-2.196]
 [-0.399]
 [-8.771]]
[[ -1.518]
 [  5.034]
 [-12.621]]
[[  0.084]
 [  5.655]
 [-33.291]]
[[ -1.422]
 [  4.017]
 [-11.048]]
[[-2.868]
 [ 3.815]
 [ 3.454]]
[[  0.354]
 [ -8.99 ]
 [-42.601]]
[[-2.625]
 [-6.505]
 [ 7.038]]
[[-2.316]
 [-2.71 ]
 [-7.76 ]]
[[  0.398]
 [ -1.098]
 [-44.442]]
[[  0.169]
 [ -0.054]
 [-38.274]]
[[  0.688]
 [ -3.732]
 [-45.44 ]]
[[-2.225]
 [ 3.877]
 [-6.614]]
[[  0.078]
 [ -1.695]
 [-37.361]]
[[  0.746]
 [ -4.026]
 [-53.632]]
[[-2.051]
 [ 1.534]
 [-9.27 ]]
[[-3.325]
 [-1.042]
 [14.777]]
[[-1.884]
 [ 2.972]
 [-8.148]]
[[ -1.884]
 [  7.76 ]
 [-10.514]]
[[-3.492]
 [ 1.493]
 [ 6.086]]
[[-2.713]
 [-8.675]
 [ 2.844]]
[[-1.785]
 [-3.192]
 [-9.623]]
[[-3.09 ]
 [-5.166]
 [ 9.535]]
[[  0.265]
 [ -1.239]
 [-40.152]]
[[  0.291]
 [ -3.877]
 [-42.712]]
[[-3.392]
 [ 3.02 ]
 [ 6.195]]
[[ -2.838]
 [-14.974]
 [  7.306]]
[[ -1.443]
 [ -4.623]
 [-

[[-2.995]
 [-8.204]
 [10.664]]
[[  0.408]
 [ -5.374]
 [-44.353]]
[[-3.72 ]
 [ 0.528]
 [11.204]]
[[ -2.177]
 [-11.643]
 [ -0.991]]
[[-2.811]
 [-9.743]
 [ 7.407]]
[[  0.169]
 [ -3.267]
 [-38.356]]
[[-1.925]
 [-4.016]
 [-7.194]]
[[-2.751]
 [ 1.219]
 [ 8.09 ]]
[[-2.482]
 [-6.905]
 [ 1.468]]
[[-3.301]
 [-3.962]
 [ 6.523]]
[[-2.847]
 [-5.286]
 [ 6.122]]
[[-2.666]
 [-9.9  ]
 [ 3.004]]
[[  0.232]
 [ -4.334]
 [-40.196]]
[[-2.847]
 [-6.287]
 [ 4.471]]
[[  0.456]
 [ -2.778]
 [-40.279]]
[[-2.462]
 [-6.022]
 [ 1.122]]
[[-2.979]
 [-5.202]
 [ 7.229]]
[[  0.284]
 [ -2.027]
 [-40.695]]
[[  0.551]
 [ -7.058]
 [-48.946]]
[[  0.33 ]
 [ -5.413]
 [-39.689]]
[[  0.643]
 [ -8.192]
 [-51.294]]
[[-2.974]
 [-3.57 ]
 [ 0.606]]
[[-2.404]
 [-5.092]
 [ 7.344]]
[[  0.322]
 [ -4.323]
 [-43.016]]
[[  0.203]
 [ -3.127]
 [-38.037]]
[[  0.315]
 [ -4.379]
 [-42.382]]
[[  0.746]
 [ -7.354]
 [-53.826]]
[[-2.225]
 [-4.209]
 [-5.841]]
[[-2.868]
 [ 2.226]
 [ 4.44 ]]
[[  0.17 ]
 [ -7.558]
 [-37.767]]
[[-2.973]
 [-1.824]
 [ 6.006

[[  0.299]
 [  1.451]
 [-43.072]]
[[-2.777]
 [-1.523]
 [-1.675]]
[[  0.746]
 [ -6.346]
 [-54.402]]
[[-2.703]
 [ 2.975]
 [ 6.336]]
[[-2.979]
 [-4.861]
 [ 8.394]]
[[-2.973]
 [-0.456]
 [ 7.059]]
[[-1.998]
 [-5.616]
 [-9.864]]
[[-2.135]
 [ 4.348]
 [-2.639]]
[[-1.751]
 [ 4.419]
 [-8.159]]
[[  0.291]
 [ -3.466]
 [-43.112]]
[[  0.232]
 [ -2.484]
 [-40.59 ]]
[[  0.224]
 [ -0.951]
 [-40.314]]
[[-3.09 ]
 [-3.184]
 [12.124]]
[[-2.171]
 [ 1.938]
 [-4.809]]
[[-1.988]
 [ 2.648]
 [-4.657]]
[[-2.163]
 [ 1.468]
 [-3.383]]
[[-2.53 ]
 [ 5.218]
 [ 0.94 ]]
[[  0.084]
 [  1.996]
 [-37.796]]
[[-3.992]
 [ 1.48 ]
 [ 9.818]]
[[ -2.049]
 [-15.342]
 [-12.529]]
[[ -2.196]
 [ -4.996]
 [-14.806]]
[[  0.456]
 [ -0.679]
 [-44.874]]
[[ -1.838]
 [  4.668]
 [-14.848]]
[[  0.106]
 [ -3.839]
 [-45.169]]
[[-2.713]
 [ 1.581]
 [-2.818]]
[[ 2.5000e-02]
 [-5.9040e+00]
 [-3.7437e+01]]
[[  0.169]
 [ -5.51 ]
 [-38.409]]
[[-1.443]
 [-1.263]
 [-9.817]]
[[-3.328]
 [ 0.849]
 [ 9.759]]
[[-2.483]
 [-8.792]
 [-0.998]]
[[-2.316]
 [ 2.152]

[[  0.203]
 [ -5.376]
 [-40.742]]
[[-2.659]
 [-6.78 ]
 [ 1.85 ]]
[[  0.284]
 [  0.278]
 [-48.033]]
[[  0.419]
 [ -6.528]
 [-52.403]]
[[  0.376]
 [ -5.254]
 [-48.399]]
[[-2.974]
 [-3.752]
 [-9.96 ]]
[[  0.299]
 [ -4.278]
 [-39.94 ]]
[[-2.751]
 [-6.195]
 [ 7.683]]
[[-1.935]
 [-6.845]
 [-7.844]]
[[-2.051]
 [-0.174]
 [-9.553]]
[[ -1.518]
 [  6.155]
 [-13.155]]
[[  0.592]
 [ -1.024]
 [-53.141]]
[[  0.084]
 [  7.231]
 [-35.098]]
[[  0.643]
 [ -3.06 ]
 [-53.755]]
[[-2.771]
 [ 3.703]
 [ 9.767]]
[[  0.355]
 [ -3.664]
 [-41.192]]
[[-1.884]
 [-1.971]
 [-8.458]]
[[-2.268]
 [ 4.923]
 [-4.925]]
[[-2.135]
 [ 6.286]
 [-4.169]]
[[  0.365]
 [ -0.984]
 [-46.723]]
[[-1.925]
 [ 3.785]
 [-8.138]]
[[  0.427]
 [ -0.415]
 [-49.02 ]]
[[ -1.656]
 [  6.741]
 [-11.777]]
[[  0.25 ]
 [  2.698]
 [-43.088]]
[[-3.18 ]
 [-1.357]
 [ 7.044]]
[[ -1.443]
 [  1.811]
 [-11.64 ]]
[[-2.588]
 [-4.189]
 [ 1.059]]
[[-3.328]
 [-1.819]
 [ 7.22 ]]
[[-2.986]
 [-3.726]
 [ 5.91 ]]
[[  0.354]
 [ -6.098]
 [-44.805]]
[[  0.356]
 [ -2.929]


array([[ 0.07,  0.28, -0.69, -0.26,  0.1 ],
       [ 0.52, -5.37,  2.68, -6.74,  9.3 ],
       [-6.28, -6.22,  9.81, 11.28, -6.7 ]])

## Avaliação

In [98]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(shuffle=True, random_state=60)
X, y = data.data, data.target

In [102]:
def model_evaluation(W, X, y, activation_func):
    correct = 0

    for i in range(0, len(y)):
        result = None
        if(activation_func == 'sigmoid'):
            result = sigmoid_activation(input_eval(W, X[i]))
        elif(activation_func == 'step'):
            result = step_activation(input_eval(W, X[i]))

        label = y[i]
        if result[label] == 1 and np.sum(result) == 1:
            correct += 1
    print(correct*100/len(y))

**Função de ativação degrau:**

1000 Iterações e Taxa de aprendizado = 0.1

In [103]:
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
  
    W = Perceptron(1000, 0.1, X_train, y_train, 'step')
    model_evaluation(W, X_test, y_test, 'step')

70.0
70.0
80.0
63.333333333333336
70.0


**Função de ativação sigmoide:**

1000 Iterações e Taxa de aprendizado = 0.1

In [104]:
for train_index, test_index in skf.split(X, y):  
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
  
    W = Perceptron(1000, 0.1, X_train, y_train, 'sigmoid')
    model_evaluation(W, X_test, y_test, 'sigmoid')

100.0
93.33333333333333
96.66666666666667
96.66666666666667
96.66666666666667


## Comparativo dos resultados

A acurácia dos modelos gerados utilizando a função sigmoide foi maior, com todos os resultados superiores a 90%, enquanto a função step não alcançou mais de 80% de precisão.

Isso se dá pois a função logística (da função sigmoide) avalia todo o espaço amostral por ser uma função contínua, enquanto a função degrau (que não é contínua), é mais brusca para problemas de classificação que utilizam funções de erro para determinar o passo de evolução.